<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Modules\Geographical\Entities\City;
use Modules\Geographical\Entities\Province;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('provinces', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->json('polygon')->nullable();
            $table->tinyInteger('status')->nullable()->default(1)->comment('status');
        });
        Schema::create('cities', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->json('polygon')->nullable();
            $table->boolean('is_center')->default(false);
            $table->foreignId('province_id')->constrained();
            $table->tinyInteger('status')->nullable()->default(1)->comment('status');
        });

        $this->insert_provinces();
        $this->insert_cities();
    }

    private function insert_provinces(): void
    {
        $provinces = Province::query()->insert([
            ['name' => 'آذربايجان شرقي'],
            ['name' => 'آذربايجان غربي'],
            ['name' => 'اردبيل'],
            ['name' => 'اصفهان'],
            ['name' => 'البرز'],
            ['name' => 'ايلام'],
            ['name' => 'بوشهر'],
            ['name' => 'تهران'],
            ['name' => 'چهارمحال بختياري'],
            ['name' => 'خراسان جنوبي'],
            ['name' => 'خراسان رضوي'],
            ['name' => 'خراسان شمالي'],
            ['name' => 'خوزستان'],
            ['name' => 'زنجان'],
            ['name' => 'سمنان'],
            ['name' => 'سيستان و بلوچستان'],
            ['name' => 'فارس'],
            ['name' => 'قزوين'],
            ['name' => 'قم'],
            ['name' => 'كردستان'],
            ['name' => 'كرمان'],
            ['name' => 'كرمانشاه'],
            ['name' => 'كهكيلويه و بويراحمد'],
            ['name' => 'گلستان'],
            ['name' => 'گيلان'],
            ['name' => 'لرستان'],
            ['name' => 'مازندران'],
            ['name' => 'مركزي'],
            ['name' => 'هرمزگان'],
            ['name' => 'همدان'],
            ['name' => 'يزد'],
        ]);
    }

    private function insert_cities(): void
    {
        $cities_center = City::query()->insert([
            ['province_id' => 4, 'name' => 'اصفهان', 'is_center' => 1],
            ['province_id' => 6, 'name' => 'ايلام', 'is_center' => 1],
            ['province_id' => 7, 'name' => 'بوشهر', 'is_center' => 1],
            ['province_id' => 8, 'name' => 'تهران', 'is_center' => 1],
            ['province_id' => 10, 'name' => 'بيرجند', 'is_center' => 1],
            ['province_id' => 11, 'name' => 'مشهد', 'is_center' => 1],
            ['province_id' => 12, 'name' => 'بجنورد', 'is_center' => 1],
            ['province_id' => 13, 'name' => 'اهواز', 'is_center' => 1],
            ['province_id' => 14, 'name' => 'زنجان', 'is_center' => 1],
            ['province_id' => 15, 'name' => 'سمنان', 'is_center' => 1],
            ['province_id' => 17, 'name' => 'شيراز', 'is_center' => 1],
            ['province_id' => 18, 'name' => 'قزوين', 'is_center' => 1],
            ['province_id' => 21, 'name' => 'كرمان', 'is_center' => 1],
            ['province_id' => 22, 'name' => 'كرمانشاه', 'is_center' => 1],
            ['province_id' => 30, 'name' => 'همدان', 'is_center' => 1],
            ['province_id' => 31, 'name' => 'يزد', 'is_center' => 1],
        ]);
        $cities = City::query()->insert([
            ['province_id' => 1, 'name' => 'تبريز'],
            ['province_id' => 2, 'name' => 'كندوان'],
            ['province_id' => 3, 'name' => 'بندر شرفخانه'],
            ['province_id' => 4, 'name' => 'مراغه'],
            ['province_id' => 5, 'name' => 'ميانه'],
            ['province_id' => 6, 'name' => 'شبستر'],
            ['province_id' => 7, 'name' => 'مرند'],
            ['province_id' => 8, 'name' => 'جلفا'],
            ['province_id' => 9, 'name' => 'سراب'],
            ['province_id' => 1, 'name' => 'هاديشهر'],
            ['province_id' => 1, 'name' => 'بناب'],
            ['province_id' => 1, 'name' => 'كليبر'],
            ['province_id' => 1, 'name' => 'تسوج'],
            ['province_id' => 1, 'name' => 'اهر'],
            ['province_id' => 1, 'name' => 'هريس'],
            ['province_id' => 1, 'name' => 'عجبشير'],
            ['province_id' => 1, 'name' => 'هشترود'],
            ['province_id' => 1, 'name' => 'ملكان'],
            ['province_id' => 1, 'name' => 'بستان آباد'],
            ['province_id' => 1, 'name' => 'ورزقان'],
            ['province_id' => 1, 'name' => 'اسكو'],
            ['province_id' => 1, 'name' => 'آذر شهر'],
            ['province_id' => 1, 'name' => 'قره آغاج'],
            ['province_id' => 1, 'name' => 'ممقان'],
            ['province_id' => 1, 'name' => 'صوفیان'],
            ['province_id' => 1, 'name' => 'ایلخچی'],
            ['province_id' => 1, 'name' => 'خسروشهر'],
            ['province_id' => 1, 'name' => 'باسمنج'],
            ['province_id' => 1, 'name' => 'سهند'],
            ['province_id' => 2, 'name' => 'اروميه'],
            ['province_id' => 2, 'name' => 'نقده'],
            ['province_id' => 2, 'name' => 'ماكو'],
            ['province_id' => 2, 'name' => 'تكاب'],
            ['province_id' => 2, 'name' => 'خوي'],
            ['province_id' => 2, 'name' => 'مهاباد'],
            ['province_id' => 2, 'name' => 'سر دشت'],
            ['province_id' => 2, 'name' => 'چالدران'],
            ['province_id' => 2, 'name' => 'بوكان'],
            ['province_id' => 2, 'name' => 'مياندوآب'],
            ['province_id' => 2, 'name' => 'سلماس'],
            ['province_id' => 2, 'name' => 'شاهين دژ'],
            ['province_id' => 2, 'name' => 'پيرانشهر'],
            ['province_id' => 2, 'name' => 'سيه چشمه'],
            ['province_id' => 2, 'name' => 'اشنويه'],
            ['province_id' => 2, 'name' => 'چایپاره'],
            ['province_id' => 2, 'name' => 'پلدشت'],
            ['province_id' => 2, 'name' => 'شوط'],
            ['province_id' => 3, 'name' => 'اردبيل'],
            ['province_id' => 3, 'name' => 'سرعين'],
            ['province_id' => 3, 'name' => 'بيله سوار'],
            ['province_id' => 3, 'name' => 'پارس آباد'],
            ['province_id' => 3, 'name' => 'خلخال'],
            ['province_id' => 3, 'name' => 'مشگين شهر'],
            ['province_id' => 3, 'name' => 'مغان'],
            ['province_id' => 3, 'name' => 'نمين'],
            ['province_id' => 3, 'name' => 'نير'],
            ['province_id' => 3, 'name' => 'كوثر'],
            ['province_id' => 3, 'name' => 'كيوي'],
            ['province_id' => 3, 'name' => 'گرمي'],
            ['province_id' => 4, 'name' => 'فريدن'],
            ['province_id' => 4, 'name' => 'فريدون شهر'],
            ['province_id' => 4, 'name' => 'فلاورجان'],
            ['province_id' => 4, 'name' => 'گلپايگان'],
            ['province_id' => 4, 'name' => 'دهاقان'],
            ['province_id' => 4, 'name' => 'نطنز'],
            ['province_id' => 4, 'name' => 'نايين'],
            ['province_id' => 4, 'name' => 'تيران'],
            ['province_id' => 4, 'name' => 'كاشان'],
            ['province_id' => 4, 'name' => 'فولاد شهر'],
            ['province_id' => 4, 'name' => 'اردستان'],
            ['province_id' => 4, 'name' => 'سميرم'],
            ['province_id' => 4, 'name' => 'درچه'],
            ['province_id' => 4, 'name' => 'کوهپایه'],
            ['province_id' => 4, 'name' => 'مباركه'],
            ['province_id' => 4, 'name' => 'شهرضا'],
            ['province_id' => 4, 'name' => 'خميني شهر'],
            ['province_id' => 4, 'name' => 'شاهين شهر'],
            ['province_id' => 4, 'name' => 'نجف آباد'],
            ['province_id' => 4, 'name' => 'دولت آباد'],
            ['province_id' => 4, 'name' => 'زرين شهر'],
            ['province_id' => 4, 'name' => 'آران و بيدگل'],
            ['province_id' => 4, 'name' => 'باغ بهادران'],
            ['province_id' => 4, 'name' => 'خوانسار'],
            ['province_id' => 4, 'name' => 'مهردشت'],
            ['province_id' => 4, 'name' => 'علويجه'],
            ['province_id' => 4, 'name' => 'عسگران'],
            ['province_id' => 4, 'name' => 'نهضت آباد'],
            ['province_id' => 4, 'name' => 'حاجي آباد'],
            ['province_id' => 4, 'name' => 'تودشک'],
            ['province_id' => 4, 'name' => 'ورزنه'],
            ['province_id' => 5, 'name' => 'طالقان'],
            ['province_id' => 5, 'name' => 'نظرآباد'],
            ['province_id' => 5, 'name' => 'اشتهارد'],
            ['province_id' => 5, 'name' => 'هشتگرد'],
            ['province_id' => 5, 'name' => 'كن'],
            ['province_id' => 5, 'name' => 'آسارا'],
            ['province_id' => 5, 'name' => 'شهرک گلستان'],
            ['province_id' => 5, 'name' => 'اندیشه'],
            ['province_id' => 5, 'name' => 'كرج'],
            ['province_id' => 5, 'name' => 'نظر آباد'],
            ['province_id' => 5, 'name' => 'گوهردشت'],
            ['province_id' => 5, 'name' => 'ماهدشت'],
            ['province_id' => 5, 'name' => 'مشکین دشت'],
            ['province_id' => 6, 'name' => 'مهران'],
            ['province_id' => 6, 'name' => 'دهلران'],
            ['province_id' => 6, 'name' => 'آبدانان'],
            ['province_id' => 6, 'name' => 'شيروان چرداول'],
            ['province_id' => 6, 'name' => 'دره شهر'],
            ['province_id' => 6, 'name' => 'ايوان'],
            ['province_id' => 6, 'name' => 'سرابله'],
            ['province_id' => 7, 'name' => 'تنگستان'],
            ['province_id' => 7, 'name' => 'دشتستان'],
            ['province_id' => 7, 'name' => 'دير'],
            ['province_id' => 7, 'name' => 'ديلم'],
            ['province_id' => 7, 'name' => 'كنگان'],
            ['province_id' => 7, 'name' => 'گناوه'],
            ['province_id' => 7, 'name' => 'ريشهر'],
            ['province_id' => 7, 'name' => 'دشتي'],
            ['province_id' => 7, 'name' => 'خورموج'],
            ['province_id' => 7, 'name' => 'اهرم'],
            ['province_id' => 7, 'name' => 'برازجان'],
            ['province_id' => 7, 'name' => 'خارك'],
            ['province_id' => 7, 'name' => 'جم'],
            ['province_id' => 7, 'name' => 'کاکی'],
            ['province_id' => 7, 'name' => 'عسلویه'],
            ['province_id' => 7, 'name' => 'بردخون'],
            ['province_id' => 8, 'name' => 'ورامين'],
            ['province_id' => 8, 'name' => 'فيروزكوه'],
            ['province_id' => 8, 'name' => 'ري'],
            ['province_id' => 8, 'name' => 'دماوند'],
            ['province_id' => 8, 'name' => 'اسلامشهر'],
            ['province_id' => 8, 'name' => 'رودهن'],
            ['province_id' => 8, 'name' => 'لواسان'],
            ['province_id' => 8, 'name' => 'بومهن'],
            ['province_id' => 8, 'name' => 'تجريش'],
            ['province_id' => 8, 'name' => 'فشم'],
            ['province_id' => 8, 'name' => 'كهريزك'],
            ['province_id' => 8, 'name' => 'پاكدشت'],
            ['province_id' => 8, 'name' => 'چهاردانگه'],
            ['province_id' => 8, 'name' => 'شريف آباد'],
            ['province_id' => 8, 'name' => 'قرچك'],
            ['province_id' => 8, 'name' => 'باقرشهر'],
            ['province_id' => 8, 'name' => 'شهريار'],
            ['province_id' => 8, 'name' => 'رباط كريم'],
            ['province_id' => 8, 'name' => 'قدس'],
            ['province_id' => 8, 'name' => 'ملارد'],
            ['province_id' => 9, 'name' => 'شهركرد'],
            ['province_id' => 9, 'name' => 'فارسان'],
            ['province_id' => 9, 'name' => 'بروجن'],
            ['province_id' => 9, 'name' => 'چلگرد'],
            ['province_id' => 9, 'name' => 'اردل'],
            ['province_id' => 9, 'name' => 'لردگان'],
            ['province_id' => 9, 'name' => 'سامان'],
            ['province_id' => 10, 'name' => 'قائن'],
            ['province_id' => 10, 'name' => 'فردوس'],
            ['province_id' => 10, 'name' => 'نهبندان'],
            ['province_id' => 10, 'name' => 'سربيشه'],
            ['province_id' => 10, 'name' => 'طبس مسینا'],
            ['province_id' => 10, 'name' => 'قهستان'],
            ['province_id' => 10, 'name' => 'درمیان'],
            ['province_id' => 11, 'name' => 'نيشابور'],
            ['province_id' => 11, 'name' => 'سبزوار'],
            ['province_id' => 11, 'name' => 'كاشمر'],
            ['province_id' => 11, 'name' => 'گناباد'],
            ['province_id' => 11, 'name' => 'طبس'],
            ['province_id' => 11, 'name' => 'تربت حيدريه'],
            ['province_id' => 11, 'name' => 'خواف'],
            ['province_id' => 11, 'name' => 'تربت جام'],
            ['province_id' => 11, 'name' => 'تايباد'],
            ['province_id' => 11, 'name' => 'قوچان'],
            ['province_id' => 11, 'name' => 'سرخس'],
            ['province_id' => 11, 'name' => 'بردسكن'],
            ['province_id' => 11, 'name' => 'فريمان'],
            ['province_id' => 11, 'name' => 'چناران'],
            ['province_id' => 11, 'name' => 'درگز'],
            ['province_id' => 11, 'name' => 'كلات'],
            ['province_id' => 11, 'name' => 'طرقبه'],
            ['province_id' => 11, 'name' => 'سر ولایت'],
            ['province_id' => 12, 'name' => 'اسفراين'],
            ['province_id' => 12, 'name' => 'جاجرم'],
            ['province_id' => 12, 'name' => 'شيروان'],
            ['province_id' => 12, 'name' => 'آشخانه'],
            ['province_id' => 12, 'name' => 'گرمه'],
            ['province_id' => 12, 'name' => 'ساروج'],
            ['province_id' => 13, 'name' => 'ايرانشهر'],
            ['province_id' => 13, 'name' => 'شوش'],
            ['province_id' => 13, 'name' => 'آبادان'],
            ['province_id' => 13, 'name' => 'خرمشهر'],
            ['province_id' => 13, 'name' => 'مسجد سليمان'],
            ['province_id' => 13, 'name' => 'ايذه'],
            ['province_id' => 13, 'name' => 'شوشتر'],
            ['province_id' => 13, 'name' => 'انديمشك'],
            ['province_id' => 13, 'name' => 'سوسنگرد'],
            ['province_id' => 13, 'name' => 'هويزه'],
            ['province_id' => 13, 'name' => 'دزفول'],
            ['province_id' => 13, 'name' => 'شادگان'],
            ['province_id' => 13, 'name' => 'بندر ماهشهر'],
            ['province_id' => 13, 'name' => 'بندر امام خميني'],
            ['province_id' => 13, 'name' => 'اميديه'],
            ['province_id' => 13, 'name' => 'بهبهان'],
            ['province_id' => 13, 'name' => 'رامهرمز'],
            ['province_id' => 13, 'name' => 'باغ ملك'],
            ['province_id' => 13, 'name' => 'هنديجان'],
            ['province_id' => 13, 'name' => 'لالي'],
            ['province_id' => 13, 'name' => 'رامشیر'],
            ['province_id' => 13, 'name' => 'حمیدیه'],
            ['province_id' => 13, 'name' => 'دغاغله'],
            ['province_id' => 13, 'name' => 'ملاثانی'],
            ['province_id' => 13, 'name' => 'شادگان'],
            ['province_id' => 13, 'name' => 'ویسی'],
            ['province_id' => 14, 'name' => 'ابهر'],
            ['province_id' => 14, 'name' => 'خدابنده'],
            ['province_id' => 14, 'name' => 'طارم'],
            ['province_id' => 14, 'name' => 'ماهنشان'],
            ['province_id' => 14, 'name' => 'خرمدره'],
            ['province_id' => 14, 'name' => 'ايجرود'],
            ['province_id' => 14, 'name' => 'زرين آباد'],
            ['province_id' => 14, 'name' => 'آب بر'],
            ['province_id' => 14, 'name' => 'قيدار'],
            ['province_id' => 15, 'name' => 'شاهرود'],
            ['province_id' => 15, 'name' => 'گرمسار'],
            ['province_id' => 15, 'name' => 'ايوانكي'],
            ['province_id' => 15, 'name' => 'دامغان'],
            ['province_id' => 15, 'name' => 'بسطام'],
            ['province_id' => 16, 'name' => 'زاهدان'],
            ['province_id' => 16, 'name' => 'چابهار'],
            ['province_id' => 16, 'name' => 'خاش'],
            ['province_id' => 16, 'name' => 'سراوان'],
            ['province_id' => 16, 'name' => 'زابل'],
            ['province_id' => 16, 'name' => 'سرباز'],
            ['province_id' => 16, 'name' => 'نيكشهر'],
            ['province_id' => 16, 'name' => 'ايرانشهر'],
            ['province_id' => 16, 'name' => 'راسك'],
            ['province_id' => 16, 'name' => 'ميرجاوه'],
            ['province_id' => 17, 'name' => 'اقليد'],
            ['province_id' => 17, 'name' => 'داراب'],
            ['province_id' => 17, 'name' => 'فسا'],
            ['province_id' => 17, 'name' => 'مرودشت'],
            ['province_id' => 17, 'name' => 'خرم بيد'],
            ['province_id' => 17, 'name' => 'آباده'],
            ['province_id' => 17, 'name' => 'كازرون'],
            ['province_id' => 17, 'name' => 'ممسني'],
            ['province_id' => 17, 'name' => 'سپيدان'],
            ['province_id' => 17, 'name' => 'لار'],
            ['province_id' => 17, 'name' => 'فيروز آباد'],
            ['province_id' => 17, 'name' => 'جهرم'],
            ['province_id' => 17, 'name' => 'ني ريز'],
            ['province_id' => 17, 'name' => 'استهبان'],
            ['province_id' => 17, 'name' => 'لامرد'],
            ['province_id' => 17, 'name' => 'مهر'],
            ['province_id' => 17, 'name' => 'حاجي آباد'],
            ['province_id' => 17, 'name' => 'نورآباد'],
            ['province_id' => 17, 'name' => 'اردكان'],
            ['province_id' => 17, 'name' => 'صفاشهر'],
            ['province_id' => 17, 'name' => 'ارسنجان'],
            ['province_id' => 17, 'name' => 'قيروكارزين'],
            ['province_id' => 17, 'name' => 'سوريان'],
            ['province_id' => 17, 'name' => 'فراشبند'],
            ['province_id' => 17, 'name' => 'سروستان'],
            ['province_id' => 17, 'name' => 'ارژن'],
            ['province_id' => 17, 'name' => 'گويم'],
            ['province_id' => 17, 'name' => 'داريون'],
            ['province_id' => 17, 'name' => 'زرقان'],
            ['province_id' => 17, 'name' => 'خان زنیان'],
            ['province_id' => 17, 'name' => 'کوار'],
            ['province_id' => 17, 'name' => 'ده بید'],
            ['province_id' => 17, 'name' => 'باب انار/خفر'],
            ['province_id' => 17, 'name' => 'بوانات'],
            ['province_id' => 17, 'name' => 'خرامه'],
            ['province_id' => 17, 'name' => 'خنج'],
            ['province_id' => 17, 'name' => 'سیاخ دارنگون'],
            ['province_id' => 18, 'name' => 'تاكستان'],
            ['province_id' => 18, 'name' => 'آبيك'],
            ['province_id' => 18, 'name' => 'بوئين زهرا'],
            ['province_id' => 19, 'name' => 'قم'],
            ['province_id' => 20, 'name' => 'سنندج'],
            ['province_id' => 20, 'name' => 'ديواندره'],
            ['province_id' => 20, 'name' => 'بانه'],
            ['province_id' => 20, 'name' => 'بيجار'],
            ['province_id' => 20, 'name' => 'سقز'],
            ['province_id' => 20, 'name' => 'كامياران'],
            ['province_id' => 20, 'name' => 'قروه'],
            ['province_id' => 20, 'name' => 'مريوان'],
            ['province_id' => 20, 'name' => 'صلوات آباد'],
            ['province_id' => 20, 'name' => 'حسن آباد'],
            ['province_id' => 21, 'name' => 'راور'],
            ['province_id' => 21, 'name' => 'بابك'],
            ['province_id' => 21, 'name' => 'انار'],
            ['province_id' => 21, 'name' => 'کوهبنان'],
            ['province_id' => 21, 'name' => 'رفسنجان'],
            ['province_id' => 21, 'name' => 'بافت'],
            ['province_id' => 21, 'name' => 'سيرجان'],
            ['province_id' => 21, 'name' => 'كهنوج'],
            ['province_id' => 21, 'name' => 'زرند'],
            ['province_id' => 21, 'name' => 'بم'],
            ['province_id' => 21, 'name' => 'جيرفت'],
            ['province_id' => 21, 'name' => 'بردسير'],
            ['province_id' => 22, 'name' => 'اسلام آباد غرب'],
            ['province_id' => 22, 'name' => 'سر پل ذهاب'],
            ['province_id' => 22, 'name' => 'كنگاور'],
            ['province_id' => 22, 'name' => 'سنقر'],
            ['province_id' => 22, 'name' => 'قصر شيرين'],
            ['province_id' => 22, 'name' => 'گيلان غرب'],
            ['province_id' => 22, 'name' => 'هرسين'],
            ['province_id' => 22, 'name' => 'صحنه'],
            ['province_id' => 22, 'name' => 'پاوه'],
            ['province_id' => 22, 'name' => 'جوانرود'],
            ['province_id' => 22, 'name' => 'شاهو'],
            ['province_id' => 23, 'name' => 'ياسوج'],
            ['province_id' => 23, 'name' => 'گچساران'],
            ['province_id' => 23, 'name' => 'دنا'],
            ['province_id' => 23, 'name' => 'دوگنبدان'],
            ['province_id' => 23, 'name' => 'سي سخت'],
            ['province_id' => 23, 'name' => 'دهدشت'],
            ['province_id' => 23, 'name' => 'ليكك'],
            ['province_id' => 24, 'name' => 'گرگان'],
            ['province_id' => 24, 'name' => 'آق قلا'],
            ['province_id' => 24, 'name' => 'گنبد كاووس'],
            ['province_id' => 24, 'name' => 'علي آباد كتول'],
            ['province_id' => 24, 'name' => 'مينو دشت'],
            ['province_id' => 24, 'name' => 'تركمن'],
            ['province_id' => 24, 'name' => 'كردكوي'],
            ['province_id' => 24, 'name' => 'بندر گز'],
            ['province_id' => 24, 'name' => 'كلاله'],
            ['province_id' => 24, 'name' => 'آزاد شهر'],
            ['province_id' => 24, 'name' => 'راميان'],
            ['province_id' => 25, 'name' => 'رشت'],
            ['province_id' => 25, 'name' => 'منجيل'],
            ['province_id' => 25, 'name' => 'لنگرود'],
            ['province_id' => 25, 'name' => 'رود سر'],
            ['province_id' => 25, 'name' => 'تالش'],
            ['province_id' => 25, 'name' => 'آستارا'],
            ['province_id' => 25, 'name' => 'ماسوله'],
            ['province_id' => 25, 'name' => 'آستانه اشرفيه'],
            ['province_id' => 25, 'name' => 'رودبار'],
            ['province_id' => 25, 'name' => 'فومن'],
            ['province_id' => 25, 'name' => 'صومعه سرا'],
            ['province_id' => 25, 'name' => 'بندرانزلي'],
            ['province_id' => 25, 'name' => 'كلاچاي'],
            ['province_id' => 25, 'name' => 'هشتپر'],
            ['province_id' => 25, 'name' => 'رضوان شهر'],
            ['province_id' => 25, 'name' => 'ماسال'],
            ['province_id' => 25, 'name' => 'شفت'],
            ['province_id' => 25, 'name' => 'سياهكل'],
            ['province_id' => 25, 'name' => 'املش'],
            ['province_id' => 25, 'name' => 'لاهیجان'],
            ['province_id' => 25, 'name' => 'خشک بيجار'],
            ['province_id' => 25, 'name' => 'خمام'],
            ['province_id' => 25, 'name' => 'لشت نشا'],
            ['province_id' => 25, 'name' => 'بندر کياشهر'],
            ['province_id' => 26, 'name' => 'خرم آباد'],
            ['province_id' => 26, 'name' => 'ماهشهر'],
            ['province_id' => 26, 'name' => 'دزفول'],
            ['province_id' => 26, 'name' => 'بروجرد'],
            ['province_id' => 26, 'name' => 'دورود'],
            ['province_id' => 26, 'name' => 'اليگودرز'],
            ['province_id' => 26, 'name' => 'ازنا'],
            ['province_id' => 26, 'name' => 'نور آباد'],
            ['province_id' => 26, 'name' => 'كوهدشت'],
            ['province_id' => 26, 'name' => 'الشتر'],
            ['province_id' => 26, 'name' => 'پلدختر'],
            ['province_id' => 27, 'name' => 'ساري'],
            ['province_id' => 27, 'name' => 'آمل'],
            ['province_id' => 27, 'name' => 'بابل'],
            ['province_id' => 27, 'name' => 'بابلسر'],
            ['province_id' => 27, 'name' => 'بهشهر'],
            ['province_id' => 27, 'name' => 'تنكابن'],
            ['province_id' => 27, 'name' => 'جويبار'],
            ['province_id' => 27, 'name' => 'چالوس'],
            ['province_id' => 27, 'name' => 'رامسر'],
            ['province_id' => 27, 'name' => 'سواد كوه'],
            ['province_id' => 27, 'name' => 'قائم شهر'],
            ['province_id' => 27, 'name' => 'نكا'],
            ['province_id' => 27, 'name' => 'نور'],
            ['province_id' => 27, 'name' => 'بلده'],
            ['province_id' => 27, 'name' => 'نوشهر'],
            ['province_id' => 27, 'name' => 'پل سفيد'],
            ['province_id' => 27, 'name' => 'محمود آباد'],
            ['province_id' => 27, 'name' => 'فريدون كنار'],
            ['province_id' => 28, 'name' => 'اراك'],
            ['province_id' => 28, 'name' => 'آشتيان'],
            ['province_id' => 28, 'name' => 'تفرش'],
            ['province_id' => 28, 'name' => 'خمين'],
            ['province_id' => 28, 'name' => 'دليجان'],
            ['province_id' => 28, 'name' => 'ساوه'],
            ['province_id' => 28, 'name' => 'سربند'],
            ['province_id' => 28, 'name' => 'محلات'],
            ['province_id' => 28, 'name' => 'شازند'],
            ['province_id' => 29, 'name' => 'بندرعباس'],
            ['province_id' => 29, 'name' => 'قشم'],
            ['province_id' => 29, 'name' => 'كيش'],
            ['province_id' => 29, 'name' => 'بندر لنگه'],
            ['province_id' => 29, 'name' => 'بستك'],
            ['province_id' => 29, 'name' => 'حاجي آباد'],
            ['province_id' => 29, 'name' => 'دهبارز'],
            ['province_id' => 29, 'name' => 'انگهران'],
            ['province_id' => 29, 'name' => 'ميناب'],
            ['province_id' => 29, 'name' => 'ابوموسي'],
            ['province_id' => 29, 'name' => 'بندر جاسك'],
            ['province_id' => 29, 'name' => 'تنب بزرگ'],
            ['province_id' => 29, 'name' => 'بندر خمیر'],
            ['province_id' => 29, 'name' => 'پارسیان'],
            ['province_id' => 29, 'name' => 'قشم'],
            ['province_id' => 30, 'name' => 'ملاير'],
            ['province_id' => 30, 'name' => 'تويسركان'],
            ['province_id' => 30, 'name' => 'نهاوند'],
            ['province_id' => 30, 'name' => 'كبودر اهنگ'],
            ['province_id' => 30, 'name' => 'رزن'],
            ['province_id' => 30, 'name' => 'اسدآباد'],
            ['province_id' => 30, 'name' => 'بهار'],
            ['province_id' => 31, 'name' => 'تفت'],
            ['province_id' => 31, 'name' => 'اردكان'],
            ['province_id' => 31, 'name' => 'ابركوه'],
            ['province_id' => 31, 'name' => 'ميبد'],
            ['province_id' => 31, 'name' => 'طبس'],
            ['province_id' => 31, 'name' => 'بافق'],
            ['province_id' => 31, 'name' => 'مهريز'],
            ['province_id' => 31, 'name' => 'اشكذر'],
            ['province_id' => 31, 'name' => 'هرات'],
            ['province_id' => 31, 'name' => 'خضرآباد'],
            ['province_id' => 31, 'name' => 'شاهديه'],
            ['province_id' => 31, 'name' => 'حمیدیه شهر'],
            ['province_id' => 31, 'name' => 'سید میرزا'],
            ['province_id' => 31, 'name' => 'زارچ']
        ]);
    }

    public function down(): void
    {
        Schema::dropIfExists('cities');
        Schema::dropIfExists('provinces');
    }

};
